name: CI

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [main, master]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  ci:
    uses: mlm-games/ci/.github/workflows/rust-ci.yml@v1
